import * as Params from "@gramio/types/params";

import type { Optional } from "#utils";

import { Context } from "../context";

import { TargetMixin } from "./target";

/** This object represents a mixin that works with all `*ChatInviteLink` methods */
class ChatInviteControlMixin {
	/** Generates new primary invite link */
	exportInviteLink(
		params?: Optional<Params.ExportChatInviteLinkParams, "chat_id">,
	) {
		return this.bot.api.exportChatInviteLink({
			chat_id: this.chatId,
			...params,
		});
	}

	/** Creates an additional invite link */
	createInviteLink(
		params?: Optional<Params.CreateChatInviteLinkParams, "chat_id">,
	) {
		return this.bot.api.createChatInviteLink({
			chat_id: this.chatId,
			...params,
		});
	}

	/** Edits non-primary invite link created by the bot */
	editInviteLink(
		link: string,
		params?: Optional<
			Params.EditChatInviteLinkParams,
			"chat_id" | "invite_link"
		>,
	) {
		return this.bot.api.editChatInviteLink({
			chat_id: this.chatId,
			invite_link: link,
			...params,
		});
	}

	/** Revokes an invite link generated by a bot */
	revokeInviteLink(
		link: string,
		params?: Optional<
			Params.RevokeChatInviteLinkParams,
			"chat_id" | "invite_link"
		>,
	) {
		return this.bot.api.revokeChatInviteLink({
			chat_id: this.chatId,
			invite_link: link,
			...params,
		});
	}
}

interface ChatInviteControlMixin extends Context, TargetMixin {}

export { ChatInviteControlMixin };
